name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Gems
        run: bundle install --jobs 4 --retry 3

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install packages
        run: yarn install

      - name: Build Middleman
        run: bundle exec middleman build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
